<?php

/**
 * @file
 * Contains di_paragraphs_classic.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function di_paragraphs_classic_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the di_paragraphs_classic module.
    case 'help.page.di_paragraphs_classic':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Classic paragraphs and shared fields') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function di_paragraphs_classic_theme($existing, $type, $theme, $path) {
  /*return [
  'field__entity_reference_revisions' => [
  'base hook' => 'paragraph',
  ],
  'field__paragraph__field_media__media' => [
  'base hook' => 'paragraph',
  ],
  'paragraph__grid_column' => [
  'base hook' => 'paragraph',
  ],
  'paragraph__grid_row' => [
  'base hook' => 'paragraph',
  ],
  'paragraph__heading' => [
  'base hook' => 'paragraph',
  ],
  'paragraph__media' => [
  'base hook' => 'paragraph',
  ],
  'paragraph__section' => [
  'base hook' => 'paragraph',
  ],
  'paragraph__text' => [
  'base hook' => 'paragraph',
  ],
  'paragraph__view' => [
  'base hook' => 'paragraph',
  ],
  ];*/
}
